language: python
python: 3.7
dist: xenial
sudo: true

install:
  - pip3 install --upgrade pip
  - pip install -r requirements.txt
script:
  - pytest --url=https://api.openbrewerydb.org/breweries 03_api/test_brewery_api.py